<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://itq.edu/factura" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://itq.edu/factura" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://itq.edu/factura">
			<xs:include schemaLocation="factura.xsd"/>
		</xs:schema>
  </wsdl:types>
  <wsdl:message name="solicitud">
    <wsdl:part name="parameter" element="tns:solicitud">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="factura">
    <wsdl:part name="parameter" element="tns:factura">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="generarFacturaPortType">
    <wsdl:operation name="generarFactura">
      <wsdl:input message="tns:solicitud">
    </wsdl:input>
      <wsdl:output message="tns:factura">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="generarFacturaBinding" type="tns:generarFacturaPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="generarFactura">
      <soap:operation soapAction="http://itq.edu/factura/generarFactura"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="generarFacturaService">
    <wsdl:port name="generarFacturaPort" binding="tns:generarFacturaBinding">
      <soap:address location="http://localhost:8088/generarFactura"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
